### PR TITLE
Resolved issues with EasyMock test

### PR DESCRIPTION
**Pull request by akshaysonvane**

### CODE REVIEW

**Comment by grechaw** [comment]
I had actually updated this test already to junit5 and maybe fixed some of it too...  can you resolve the conflicts and take a look?

**Comment by akshaysonvane** [comment]
I've resolved the conflicts and have also enabled all the tests.
Feel free to disable them as needed.

**Comment by grechaw** [comment]
would you mind making the PR against the marklogic repo?

**Comment by akshaysonvane** [comment]
Sure.

**Pull request closed without merging**
